POST https://notes-test-nz7r.onrender.com/api/notes
Content-Type: application/json

    {
        "content": "i sdafasdf to use postman",
        "important": true
    }

###

get https://notes-test-nz7r.onrender.com/


###

:method :url :status :res[content-length] - :response-time ms
